config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'posts#index'

  resources :posts do
    resources :comments, :except => [:show, :index]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :presence => true
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :presence => true
  validates :body, :presence => true

  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new( comment_params )
    if @comment.save
      respond_to do |format|
        format.html { redirect_to post_path(@comment.post) }
          flash[:notice] = "Your comment is posted!"
        format.js
      end
    else
      flash[:alert] = "Something went wrong."
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update( comment_params )
      flash[:notice] = "Comment updated"
      redirect_to post_path(@comment.post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to posts_path }
      flash[:notice] = "Your post has been deleted!"
      format.js
    end
  end

private
  def comment_params
    params.require(:comment).permit(:body, :post_id, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new(params[:post])
  end

  def create
    @post = Post.new( post_params )
    @user =
    if @post.save
      flash[:notice] = "Your post has been added!"
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update( post_params )
      flash[:notice] = "Your post has been updated!"
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

  end


private
  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="panel panel-primary" id="comment_panel_<%= comment.id %>">
  <div class="panel-heading">
    <%= comment.user.email %>
  </div>
  <div class="panel-body">
    <%= comment.body %>
    <% if comment.user == current_user %>
    <%= link_to "Edit Comment", edit_post_comment_path(comment.post_id, comment.id) %>
    <%= link_to "Delete Comment", post_comment_path(comment.post_id, comment.id),
    :data => {:confirm => "Sure you wanna?",
      :method => "delete"} %>
      <% end %>
    </div>
  </div>

app/views/comments/_form.html.erb
<%= render 'layouts/errors', :object => @comment %>

<div id="form-box">
  <%= form_for [@post, @comment], remote: true do |f| %>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_field :body, :class => "form-control", :rows => 5 %>
    </div>
    <div class="form-group">
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#form-box').remove();
$('#new_comment').show();
$('#comment_list').prepend('<%= j render(@comment) %>');

app/views/comments/destroy.js.erb
$('#comment_panel_<%= @comment.id %>').remove()

app/views/comments/edit.html.erb
<div class="container">
  <h3> Edit your comment </h3>

  <%= render 'form' %>
</div>

app/views/comments/new.html.erb
<div class="container">

  <h4>Write your comment here!</h4>

  <%= render 'form' %>


</div>

app/views/comments/new.js.erb
$('#new_comment').hide();
$('#comment_list').prepend('<%= j render("form") %>');

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JournalBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= flash[:notice] %>
    <%= flash[:alert] %>
    <nav class="navbar navbar-default" role="navigation">
      <ul class="nav navbar-nav navbar-left">
        <a class="navbar-brand" href="/">The Journal Blog</a>
      </ul>
      <ul class="navbar navbar-nav navbar pull-right">
        <% if user_signed_in? %>
        <li class="nav-li"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li class="nav-li"> <%= link_to "Sign up", new_user_registration_path %> </li>
        <li class="nav-li"> <%= link_to "Log In", new_user_session_path %> </li>
        <% end %>
      </ul>
    </nav>

    <% if user_signed_in? %>
      <p class="right-align"> Logged in as <%= current_user.email %><p>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_comment.html.erb
<div class="panel panel-primary" id="comment_panel_<%= comment.id %>">
  <div class="panel-heading">
  <%= comment.user.email %>
  </div>
  <div class="panel-body">
    <%= comment.body %>
    <div class="panel-bottom">
      <% if comment.user == current_user %>
        <small class="pull-right">
          <%= link_to "Edit Comment", edit_post_comment_path(comment.post_id, comment.id) %> |
          <%= link_to "Delete Comment", post_comment_path(comment.post_id, comment.id),
                :data => {:confirm => "Sure you wanna?",
                :method => "delete"}, remote: true %>
        </small>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= render 'layouts/errors', :object => @post %>

<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, :class => "form-control", :rows => 8 %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">

  <h2>Edit your post!</h2>

  <% if @post.errors.any? %>
    <h3>Please fix these errors, first.</h3>
    <ul>
      <%= @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= render 'form' %>

</div>

app/views/posts/index.html.erb
<div class="container">
  <h1>How About a Journal Blog?</h1>

  <% if @posts.any? %>
    <h4>Your Posts:</h4>

    <ul>
      <% @posts.each do |post| %>
        <li><%= link_to post.title, post_path(post.id) %></li>
      <% end %>
    </ul>
  <% else %>
    <p>
      No posts yet!<br>
    </p>
  <% end %>
  <%= link_to "Write post", new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h2>Write a post!</h2>

  <% if @post.errors.any? %>
    <h3>Oops. Some errors occured. Try again?</h3>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <%= render 'form' %>

</div>

app/views/posts/show.html.erb
<div class="container">

  <div class="col-md-12">
    <%= flash[:notice] %>
  </div>

  <div class="col-md-12">
    <h3><%= @post.title %></h3>
    <p><%= @post.body %></p>
  </div>


  <h4>Comments:</h4>
  
  <% if user_signed_in? %>
    <div class="col-md-12">
      <%= link_to "Add Comment", new_post_comment_path(@post),
            id: 'new_comment',
            class: "btn btn-sm btn-success",
            remote: true %>
    </div>
  <% else %>
    <div class="col-md-12">
      <%= link_to "Sign in to comment", new_user_session_path %>
    </div>
  <% end %>


  <div class="col-md-12" id="comment_list">
    <% if @post.comments.any? %>
    <%= render partial: "comment", collection: @post.comments %>
    <% end %>
  </div>


    <div class="col-md-12">
    <% if @post.user == current_user %>
        <%= link_to "Edit Post", edit_post_path,
                                      :class => "btn btn-sm btn-info" %>
        <%= link_to "Delete Post", post_path(@post),
                                      :data => {:confirm => "Sure you wanna do that?",
                                                :method => "delete" },
                                      :class => "btn btn-sm btn-danger",
                                      :style => "margin: 10px 0;" %>
    <% end %>
      <%= link_to "Return to posts", posts_path,
                                  :class => "btn btn-sm btn-primary" %>
  </div>

</div>